dist: xenial
services:
  - xvfb
language: node_js
node_js:
  - 8.15.1
script: 
  - cat package-lock.json
  - npm run travis
addons:
  firefox: latest
before_install:
    - node -v
    - npm -v
branches:
  only:
    - master
    - /^[cC]\d{3}[\w-]*/
    - /^\d{4}\.\d{2}.[\d|x]{2}$/
