dist: xenial
services:
  - xvfb
language: node_js
node_js:
  - 8.15.1
script: 
  - npm run travis
addons:
  firefox: latest
before_install:
    - node -v
    - npm -v
install:
  # Tell npm to ignore package-lock.json to avoid making local file
  # changes that would dirty the git workspace.
  - npm config set package-lock false
  - npm install
branches:
  only:
    - master
    - /^[cC]\d{3}[\w-]*/
    - /^\d{4}\.\d{2}.[\d|x]{2}$/
